spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-user-redis
    username: postgres-user-redis
    password: postgres-user-redis
  jpa:
    hibernate:
      ddl-auto: create-drop
  cache:
    type: redis
#  redis:
#    host: localhost
#    database: 0
#    port: 6379
#    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#    timeout: 30000

