management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus

redis:
  hostname: localhost
  port: 6379
  database: 0
  password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  timeout: 10000