spring:
  redis:
    database: 0
    host: localhost
    port: 6370
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    timeout: 60000

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus