spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres-user-service
    username: postgres-user-service
    password: postgres-user-service
  jpa:
    hibernate:
      ddl-auto: create-drop