#spring:
#  redis:
#    database: 0
#    host: redis
#    port: 6379
#    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#    timeout: 60000

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: prometheus

memcached.cache:
  servers: localhost:11211
  provider: static
  # default expiration set to '1d' (1 day i.e. '86400' seconds) and custom ones for cache_name1 and cache_name2
  expiration: 1d
  expiration-per-cache:
    cache_name1: 1h
    cache_name2: 30h
  metrics-cache-names: cache_name1, cache_name2


spring:
  servlet:
    multipart:
      max-file-size: 150000000
      max-request-size: 150000000