spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres-user-memcached
    username: postgres-user-memcached
    password: postgres-user-memcached
  jpa:
    hibernate:
      ddl-auto: create-drop